version: "3.8"

services:
  workspace:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DOCKER_VERSION: ${DOCKER_VERSION}
        DOCKER_COMPOSE_VERSION: ${DOCKER_COMPOSE_VERSION}
        CTOP_VERSION: ${CTOP_VERSION}
    
