version: '3.8'

services:
  workspace:
    image: registry.cn-hangzhou.aliyuncs.com/axf888/workspace
    volumes:
      - /etc/timezone:/etc/timezone
      - /root/.vscode-server/:/root/.vscode-server/
      - /work/projects/:/work/projects/
      - /work/dockers-apps/:/work/docker-apps/
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    tty: true
