version: '3.8'

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge

services:
  workspace:
    image: registry.cn-hangzhou.aliyuncs.com/axf888/workspace
    volumes:
      - /etc/timezone:/etc/timezone
      - /work/cache/vscode-server/:/root/.vscode-server/
      - /work/cache/composer/:/root/.composer/
      - /work/cache/npm/:/root/.npm/
      - /work/workspace/:/work/workspace/
      - /work/projects/:/work/projects/
      - /work/dockers/:/work/dockers/
      - /var/run/docker.sock:/var/run/docker.sock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    networks:
      - frontend
      - backend
    tty: true

